---
title: "BDA_chap11"
output: html_document
---
## Gibbs sampling (p. 277)

```{r, message=FALSE}
rm(list = ls())
library(ggplot2)
library(tidyverse)
set.seed(1)
```



```{r}
y1 <- 0
y2 <- 0
rho <- .8

SampleTheta <- function(y, v, theta){
  new <- rnorm(1, y + v * (theta - y), 1 - v^2)
  return(new)
}

n <- 500
```

## sampling theta
### 
```{r, message = FALSE}
databox <- replicate(4, data.frame(theta1 = rep(NA, 2*n+1), theta2 = rep(NA, 2*n+1) , pattern = rep(NA, 2*n+1)), simplify  = FALSE)

names(databox) <- paste0("databox", 1:4)
theta1 <- c(2.5, 2.5, -2.5, -2.5)
theta2 <- c(2.5, -2.5, 2.5, -2.5)
thetas <- matrix(c(theta1, theta2), 4)

# sampling
for (j in 1:4){
  data <- databox[[j]] # choose dataframe
  data[1, 1:2] <- thetas[j, ] # set the initial value
  data[,3] <- rep(j, 2 * n +1 ) # set pattern
  for (i in 1:n ){
    theta_old2 <- data[2*i-1,2]
    theta_new1 <- SampleTheta(y2, rho, theta_old2)
    data[2*i,1] <- theta_new1
    data[2*i,2] <- theta_old2
    theta_new2 <- SampleTheta(y1, rho, theta_new1)
    data[2*i+1, 2] <- theta_new2
    data[2*i+1, 1] <- theta_new1
  }
  databox[[j]] <- data
}
```

```{r}
datafull <- bind_rows(databox[[1]], databox[[2]], databox[[3]], databox[[4]])
datafull2 <- bind_rows(databox[[1]][701:1000,], databox[[2]][701:1000,], databox[[3]][701:1000,], databox[[4]][701:1000,])
datafull$pattern <- as.factor(datafull$pattern)
datafull2$pattern <- as.factor(datafull2$pattern)

```



```{r}
p_first <- list(0)
for (i in 1:4){
  p_first[[i]] <- ggplot(databox[[i]][1:5,], aes(x = theta1, y = theta2)) + 
                      geom_path() +
                      geom_point() +
                      xlim(c(-4, 4)) + 
                      ylim(c(-4, 4))
  print(p_first[[i]])
}

```

```{r}
p_last <- list(0)
for (i in 1:4){
  p_last[[i]] <- ggplot(databox[[i]][402:501,], aes(x = theta1, y = theta2)) + 
                geom_path() +
                geom_point() +
                xlim(c(-4, 4)) + 
                ylim(c(-4, 4))
}
```




```{r} 
ggplot(datafull, aes(x = theta1, y = theta2)) + 
  geom_path(aes(color = pattern), alpha = .4) +
  geom_point(aes(color = pattern), alpha = .4) +
  xlim(c(-4, 4)) + 
  ylim(c(-4, 4))


ggplot(datafull2, aes(x = theta1, y = theta2)) + 
  geom_path(aes(color = pattern), alpha = .4) +
  geom_point(aes(color = pattern), alpha = .4) +
  xlim(c(-4, 4)) + 
  ylim(c(-4, 4))

```


# Hereafter Garbage

## sampling stage
### initial parameter theta1 = theta2 = 2.5
```{r}
theta1 <- 2.5
theta2 <- 2.5

databox1 <- data.frame(theta1 = rep(NA, 2*n+1), theta2 = rep(NA, 2*n+1) , pattern = rep(1, 2*n+1))
databox1[1, 1] <- theta1
databox1[1, 2] <- theta2

for (i in 1:n ){
  theta_old2 <- databox1[2*i-1,2]
  theta_new1 <- SampleTheta(y2, rho, theta_old2)
  databox1[2*i,1] <- theta_new1
  databox1[2*i,2] <- theta_old2
  theta_new2 <- SampleTheta(y1, rho, theta_new1)
  databox1[2*i+1, 2] <- theta_new2
  databox1[2*i+1, 1] <- theta_new1
}
```

### initial parameter theta1= 2.5, theta2 = -2.5
```{r}
theta1 <- 2.5
theta2 <- -2.5

databox2 <- data.frame(theta1 = rep(NA, 2*n+1), theta2 = rep(NA, 2*n+1) , pattern = rep(2, 2*n+1))
databox2[1, 1] <- theta1
databox2[1, 2] <- theta2

for (i in 1:n ){
  theta_old2 <- databox2[2*i-1,2]
  theta_new1 <- SampleTheta(y2, rho, theta_old2)
  databox2[2*i,1] <- theta_new1
  databox2[2*i,2] <- theta_old2
  theta_new2 <- SampleTheta(y1, rho, theta_new1)
  databox2[2*i+1, 2] <- theta_new2
  databox2[2*i+1, 1] <- theta_new1
}

```


### initial parameter theta1= -2.5, theta2 = 2.5
```{r}
theta1 <- -2.5
theta2 <- 2.5

databox3 <- data.frame(theta1 = rep(NA, 2*n+1), theta2 = rep(NA, 2*n+1) , pattern = rep(3, 2*n+1))
databox3[1, 1] <- theta1
databox3[1, 2] <- theta2

for (i in 1:n ){
  theta_old2 <- databox3[2*i-1,2]
  theta_new1 <- SampleTheta(y2, rho, theta_old2)
  databox3[2*i,1] <- theta_new1
  databox3[2*i,2] <- theta_old2
  theta_new2 <- SampleTheta(y1, rho, theta_new1)
  databox3[2*i+1, 2] <- theta_new2
  databox3[2*i+1, 1] <- theta_new1
}
```


### initial parameter theta1= theta2 = -2.5
```{r}
theta1 <- -2.5
theta2 <- -2.5

databox4 <- data.frame(theta1 = rep(NA, 2*n+1), theta2 = rep(NA, 2*n+1) , pattern = rep(4, 2*n+1))
databox4[1, 1] <- theta1
databox4[1, 2] <- theta2

for (i in 1:n ){
  theta_old2 <- databox4[2*i-1,2]
  theta_new1 <- SampleTheta(y2, rho, theta_old2)
  databox4[2*i,1] <- theta_new1
  databox4[2*i,2] <- theta_old2
  theta_new2 <- SampleTheta(y1, rho, theta_new1)
  databox4[2*i+1, 2] <- theta_new2
  databox4[2*i+1, 1] <- theta_new1
}
```

## Draw figure

```{r}
datafull <- bind_rows(databox1, databox2, databox3, databox4)
datafull2 <- bind_rows(databox1[701:1000,], databox2[701:1000,], databox3[701:1000,], databox4[701:1000,])
datafull$pattern <- as.factor(datafull$pattern)
datafull2$pattern <- as.factor(datafull2$pattern)
```


## Plot for pattern 1
```{r}
ggplot(databox1[1:5,], aes(x = theta1, y = theta2)) + 
  geom_point() +
  xlim(c(-4, 4)) + 
  ylim(c(-4, 4))

ggplot(databox1[701:1001,], aes(x = theta1, y = theta2)) + 
  geom_point() +
  xlim(c(-4, 4)) + 
  ylim(c(-4, 4))

ggplot(databox1, aes(x = theta1, y = theta2)) + 
  geom_point() +
  xlim(c(-4, 4)) + 
  ylim(c(-4, 4))


```


## plot for pattern 2
```{r}
ggplot(databox2[1:5,], aes(x = theta1, y = theta2)) + 
  geom_point() +
  xlim(c(-4, 4)) + 
  ylim(c(-4, 4))

ggplot(databox2[701:1001,], aes(x = theta1, y = theta2)) + 
  geom_point() +
  xlim(c(-4, 4)) + 
  ylim(c(-4, 4))

ggplot(databox2, aes(x = theta1, y = theta2)) + 
  geom_point() +
  xlim(c(-4, 4)) + 
  ylim(c(-4, 4))
```

## plot for pattern 3
```{r}
ggplot(databox3[1:5,], aes(x = theta1, y = theta2)) + 
  geom_point() +
  xlim(c(-4, 4)) + 
  ylim(c(-4, 4))

ggplot(databox3[701:1001,], aes(x = theta1, y = theta2)) + 
  geom_point() +
  xlim(c(-4, 4)) + 
  ylim(c(-4, 4))

ggplot(databox3, aes(x = theta1, y = theta2)) + 
  geom_point() +
  xlim(c(-4, 4)) + 
  ylim(c(-4, 4))
```

## plot for pattern 4
```{r}
ggplot(databox4[1:5,], aes(x = theta1, y = theta2)) + 
  geom_point() +
  xlim(c(-4, 4)) + 
  ylim(c(-4, 4))

ggplot(databox4[701:1001,], aes(x = theta1, y = theta2)) + 
  geom_point() +
  xlim(c(-4, 4)) + 
  ylim(c(-4, 4))

ggplot(databox4, aes(x = theta1, y = theta2)) + 
  geom_point() +
  xlim(c(-4, 4)) + 
  ylim(c(-4, 4))
```


## plot merging all patterns
```{r}
ggplot(datafull, aes(x = theta1, y = theta2)) + 
  geom_path(aes(color = pattern), alpha = .4) +
  xlim(c(-4, 4)) + 
  ylim(c(-4, 4))


ggplot(datafull2, aes(x = theta1, y = theta2)) + 
  geom_path(aes(color = pattern), alpha = .4) +
    xlim(c(-4, 4)) + 
  ylim(c(-4, 4))


```

